name: controle_estoque
description: Controle de Estoque App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  sqflite: ^2.3.0
  intl: ^0.20.2
  provider: ^6.0.0
  path: ^1.8.3
  image_picker: ^1.1.2
  sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/senac.png