// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0xQsezXHb7cXsU9jPWitFplUKYLqxHu8',
    appId: '1:876048519514:web:26cdac7de861265a716363',
    messagingSenderId: '876048519514',
    projectId: 'controle-estoque-9e979',
    authDomain: 'controle-estoque-9e979.firebaseapp.com',
    storageBucket: 'controle-estoque-9e979.firebasestorage.app',
    measurementId: 'G-BJG6762JZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXtAzGWKUEG22VSxUszh9vn8CRIMRN9A',
    appId: '1:876048519514:android:3b9c613e230c16a7716363',
    messagingSenderId: '876048519514',
    projectId: 'controle-estoque-9e979',
    storageBucket: 'controle-estoque-9e979.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0xQsezXHb7cXsU9jPWitFplUKYLqxHu8',
    appId: '1:876048519514:web:52b2e90eacdc04a8716363',
    messagingSenderId: '876048519514',
    projectId: 'controle-estoque-9e979',
    authDomain: 'controle-estoque-9e979.firebaseapp.com',
    storageBucket: 'controle-estoque-9e979.firebasestorage.app',
    measurementId: 'G-J8C853ZJBH',
  );
}
